name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: "Next.js Lint"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 17
      - run: npm ci
      - run: yarn run eslint .
